// ACTIONS TO MODIFY VALUES IN STATE
const LOGIN_TO_TWITTER = "logIntoTwitter";
const LOGOUT_OF_TWITTER = "logoutOfTwitter";
const UPDATE_TWITTER_SCREEN_NAME = "updateTwitterScreenName";
const UPDATE_TWITTER_USER_ID = "updateTwitterUserId";
const UPDATE_USER_TWEETS = "updateUserTweets";
const UPDATE_USER_FAVORITES = "updateUserFavorites";
const UPDATE_TWITTER_USER_KEYS = "updateTwitterUserKeys";
const UPDATE_TWITTER_USER_CLIENT = "updateUserClient";
const UPDATE_WHITELISTED_TWEETS = "updateWhitelistedTweets";
const UPDATE_WHITELISTED_FAVORITES = "updateWhitelistedFavorites";
const INCREMENT_CURRENTLY_DELETING_ITEMS_DELETED =
  "incrementCurrentlyDeletingItemsDeleted";
const RESET_CURRENTLY_DELETING_ITEMS_DELETED =
  "resetCurrentlyDeletingItemsDeleted";
const UPDATE_CURRENTLY_DELETING_TOTAL_ITEMS =
  "updateCurrentlyDeletingTotalTweets";
const UPDATE_TWITTER_TIME_RANGE_ENABLED = "updateTwitterTimeRangeEnabled";
const UPDATE_TWITTER_TIME_RANGE = "updateTwitterTimeRange";
const UPDATE_TWITTER_SCORE_ENABLED = "updateTwitterScoreEnabled";
const UPDATE_TWITTER_FAVORITES_SCORE = "updateTwitterFavoritesScore";
const UPDATE_TWITTER_RETWEETS_SCORE = "updateTwitterRetweetsScore";
const LOGIN_TO_REDDIT = "loginToReddit";
const LOGOUT_OF_REDDIT = "logoutOfReddit";
const UPDATE_REDDIT_USER_NAME = "updateRedditUsername";
const UPDATE_REDDIT_ACCESS_TOKEN = "updateRedditAccessToken";

// ACTUAL VALUES IN STATE
const TWITTER_LOGGED_IN = "twitterLoggedIn";
const TWITTER_SCREEN_NAME = "twitterScreenName";
const TWITTER_USER_ID = "twitterUserId";
const USER_TWEETS = "userTweets";
const USER_FAVORITES = "userFavorites";
const TWITTER_USER_KEYS = "twitterUserKeys";
const TWITTER_USER_CLIENT = "twitterUserClient";
const WHITELISTED_TWEETS = "whitelistedTweets";
const WHITELISTED_FAVORITES = "whitelistedFavorites";
const CURRENTLY_DELETING = "currentlyDeleting";
const TWITTER_TIME_RANGE_ENABLED = "twitterTimeRangeEnabled";
const TWITTER_TIME_RANGE = "twitterTimeRange";
const TWITTER_SCORE_ENABLED = "twitterScoreEnabled";
const TWITTER_FAVORITES_SCORE = "twitterFavoritesScore";
const TWITTER_RETWEETS_SCORE = "twitterRetweetsScore";
const REDDIT_LOGGED_IN = "redditLoggedIn";
const REDDIT_USER_NAME = "redditUserName";
const REDDIT_ACCESS_TOKEN = "redditAccessToken";

// other constants
const TWEETS_ROUTE = "statuses/user_timeline";
const FAVORITES_ROUTE = "favorites/list";

const constants = {
  LOGIN_TO_TWITTER,
  LOGOUT_OF_TWITTER,
  UPDATE_TWITTER_SCREEN_NAME,
  UPDATE_TWITTER_USER_ID,
  UPDATE_USER_TWEETS,
  UPDATE_USER_FAVORITES,
  UPDATE_TWITTER_USER_KEYS,
  UPDATE_TWITTER_USER_CLIENT,
  UPDATE_WHITELISTED_TWEETS,
  UPDATE_WHITELISTED_FAVORITES,
  INCREMENT_CURRENTLY_DELETING_ITEMS_DELETED,
  RESET_CURRENTLY_DELETING_ITEMS_DELETED,
  UPDATE_CURRENTLY_DELETING_TOTAL_ITEMS,
  UPDATE_TWITTER_TIME_RANGE_ENABLED,
  UPDATE_TWITTER_TIME_RANGE,
  UPDATE_TWITTER_SCORE_ENABLED,
  UPDATE_TWITTER_FAVORITES_SCORE,
  UPDATE_TWITTER_RETWEETS_SCORE,
  LOGIN_TO_REDDIT,
  LOGOUT_OF_REDDIT,
  UPDATE_REDDIT_USER_NAME,
  UPDATE_REDDIT_ACCESS_TOKEN,
  TWITTER_LOGGED_IN,
  TWITTER_SCREEN_NAME,
  TWITTER_USER_ID,
  USER_TWEETS,
  USER_FAVORITES,
  TWITTER_USER_KEYS,
  TWITTER_USER_CLIENT,
  WHITELISTED_TWEETS,
  WHITELISTED_FAVORITES,
  CURRENTLY_DELETING,
  TWITTER_TIME_RANGE_ENABLED,
  TWITTER_TIME_RANGE,
  TWITTER_SCORE_ENABLED,
  TWITTER_FAVORITES_SCORE,
  TWITTER_RETWEETS_SCORE,
  REDDIT_LOGGED_IN,
  REDDIT_USER_NAME,
  REDDIT_ACCESS_TOKEN,
  TWEETS_ROUTE,
  FAVORITES_ROUTE
};

export default constants;
