// ACTIONS TO MODIFY VALUES IN STATE
const LOGIN_TO_TWITTER = "logIntoTwitter";
const UPDATE_TWITTER_SCREEN_NAME = "updateTwitterScreenName";
const UPDATE_USER_TWEETS = "updateUserTweets";
const UPDATE_USER_FAVORITES = "updateUserFavorites";
const UPDATE_USER_CLIENT = "updateUserClient";
const UPDATE_WHITELISTED_TWEETS = "updateWhitelistedTweets";
const UPDATE_WHITELISTED_FAVORITES = "updateWhitelistedFavorites";
const INCREMENT_CURRENTLY_DELETING_TOTAL_ITEMS = "incrementCurrentlyDeletingTotalItems";
const RESET_CURRENTLY_DELETING_TOTAL_ITEMS = "resetCurrentlyDeletingTotalItems";
const UPDATE_CURRENTLY_DELETING_TOTAL_ITEMS = "updateCurrentlyDeletingTotalTweets";

// ACTUAL VALUES IN STATE
const TWITTER_LOGGED_IN = 'twitterLoggedIn';
const TWITTER_SCREEN_NAME = 'twitterScreenName';
const USER_TWEETS = 'userTweets';
const USER_FAVORITES = 'userFavorites';
const TWITTER_USER_CLIENT = 'twitterUserClient';
const WHITELISTED_TWEETS = 'whitelistedTweets';
const WHITELISTED_FAVORITES = 'whitelistedFavorites';
const CURRENTLY_DELETING = 'currentlyDeleting';

const constants = {
  LOGIN_TO_TWITTER,
  TWITTER_SCREEN_NAME,
  UPDATE_USER_TWEETS,
  UPDATE_USER_FAVORITES,
  UPDATE_USER_CLIENT,
  UPDATE_WHITELISTED_TWEETS,
  UPDATE_WHITELISTED_FAVORITES,
  INCREMENT_CURRENTLY_DELETING_TOTAL_ITEMS,
  RESET_CURRENTLY_DELETING_TOTAL_ITEMS,
  UPDATE_CURRENTLY_DELETING_TOTAL_ITEMS,
  TWITTER_LOGGED_IN,
  UPDATE_TWITTER_SCREEN_NAME,
  USER_TWEETS,
  USER_FAVORITES,
  TWITTER_USER_CLIENT,
  WHITELISTED_TWEETS,
  WHITELISTED_FAVORITES,
  CURRENTLY_DELETING,
};

export default constants;